### ISSUE TITLE
Create new Case within CBRS system with a blank Case Details Screen

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/CBRADMS#67] opened 2016-10-21 00:42 UTC
There is a desire for a blank "Case Details" screen, where a logged-in user could populate the required field for case creation, save, and then be in the case details screen as if the case was just submitted by a user.

**Comment by HansVraga** [comment] 2016-10-21 00:43
Will ask if our interpretation of their feedback is correct before proceeding with this "Easy plus" level of difficulty task.

**Comment by HansVraga** [comment] 2016-10-24 20:56
This is a desired enhancement for the future, but not necessary on initial release.

**Comment by aaronstephenson** [comment] 2016-11-05 06:43
This is a duplicate of #69 which is already implemented.

**Closed by aaronstephenson** 2016-11-05 06:43 UTC
