### ISSUE TITLE
Remove Status "Awaiting Level 2 QC"

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/CBRADMS#101] opened 2017-02-17 01:04 UTC
From user feedback:
>We are unable to enter a final letter date or the close date until a Level 2 QC signoff date has been entered. Currently, it is rare to have a Level 2 QC completed. Level 2 QC should not be a required field, only optional. Also, that means that the draft final letter should be available at the QC1 level 

>When we try to enter a 2017 date in the Signoff Date or Final Letter Date fields, we get a warning that the date is invalid. This message does not appear for 2016 dates.

**Comment by HansVraga** [comment] 2017-02-17 01:04
For the second issue - I hope they weren't trying to enter a future date...

**Comment by aaronstephenson** [comment] 2017-03-13 04:41
The final letter and close date fields are now active if the current status is either 'Awaiting Final Letter' OR 'Awaiting Level 2 QC'.

I'm going to need more thorough feedback about the dates. The current validateDate function is rather complicated because of the various relationships between date field, but basically, if a user tries to fill in a date field but the previous date status date field has not been entered (e.g., trying to enter QC2 signoff before QC1 signoff), the user is warned and unable to enter a date in the later field.

**Comment by HansVraga** [comment] 2017-03-13 15:56
How hard would it be to change the behavior of :
>the user is warned and unable to enter a date in the later field.
to
>the user is warned but may enter a date in the later field

If we can do this for date fields in general, this allows them to break their own workflows if they need it...

**Comment by HansVraga** [comment] 2017-03-13 20:05
(the above question may address #102 as well)

**Comment by aaronstephenson** [comment] 2017-03-14 03:33
I have changed the behavior of the date validation to allow the user to enter any date they wish. They will still get a warning, though (which will appear as a toast notification once @mitch-wim merges his branch).

**Comment by aaronstephenson** [comment] 2017-03-23 03:02
From user feedback:
>The Level 2 QC Field has been made optional, but when entering the Final Letter Date, you get the following error message: “Final Letter Date should not be entered until Level 2 QC Signoff Date has been entered!” Please remove this warning. In addition, please remove “Awaiting Level 2 QC” from the Current Status list. Once there is a date in the Level 1 QC Signoff Date field, the status should change to “Awaiting Final Letter.” We need this change because Level 2 QC is optional and will not happen on a regular basis, and because there would not be a way to bypass the “Awaiting Level 2 QC” status to go to the “Awaiting Final Letter” status since we would not be entering a date in the Level 2 QC field.

**Comment by aaronstephenson** [comment] 2017-03-23 03:03
Also:
>APPEARS THAT THERE ARE STILL PROBLEMS WITH INVALID DATE WARNINGS. For example, Case ID 3400 gave this warning “2016-01-10 (2016-01-10) is not a valid date. Please enter a valid date.” The warning appeared even though a new date was not entered in the database. Because the warnings are not working properly, remove them.

**Comment by aaronstephenson** [comment] 2017-03-23 05:54
The invalid date warning was caused by asynchronous loading of data into the various form fields on the initial load of the page. I have now fixed the problem. I strongly advise against removing validation warnings just because there have been a couple bugs; that is what this user testing is meant to uncover.

I have also removed the warning for the case of Final Letter Date assigned without Level 2 QC Signoff Date assigned as requested.

@hans However, I have not yet removed the Awaiting Level 2 QC status from the system because it is an integral part of the current system, and much of the validation logic relies upon it. I want to discuss this further, especially any potential repercussion, before proceeding.

**Comment by HansVraga** [comment] 2017-04-06 19:25
After discussion with CBRS folks, I've renamed this issue to reflect the task. They no longer need the buisness rule enforcing a level 2 QC. If Level 2 QC is needed, they are going to put it on the personnel involved to ensure it happens. Remove "Awaiting Level 2 QC" status, and rules enforcing Level 2 QC fields being filled out.

**Comment by aaronstephenson** [comment] 2017-06-21 07:25
Done. But please give this a thorough test, because dynamic testing of status is pervasive throughout the application (well over a dozen different places), so it is possible I missed something.

**Closed by aaronstephenson** 2017-06-21 07:25 UTC
